---
- name: Install and configure OpenVPN server
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Get public and private IP address
      shell: |
        ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | sed -n "1"p
        wget -T 10 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/"
      register: my_command_output
      changed_when: false

    - name: Print IP address and hostname
      debug:
        msg: "IP: {{ my_command_output.stdout_lines[0] }}, Hostname: {{ my_command_output.stdout_lines[1] }}"

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openvpn
          - openssl
          - ca-certificates
          - iptables
        state: present
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Create the destination directory
      file:
        path: "/etc/openvpn/server/easy-rsa/"
        state: directory
        mode: "0755"

    - name: Download EasyRSA archive
      get_url:
        url: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.5/EasyRSA-3.1.5.tgz"
        dest: "/tmp/EasyRSA-3.1.5.tgz"
        mode: "0755"

    - name: Extract EasyRSA archive
      unarchive:
        src: "/tmp/EasyRSA-3.1.5.tgz"
        dest: "/etc/openvpn/server/easy-rsa/"
        extra_opts: [--strip-components=1]
    
    - name: Set permissions for EasyRSA
      file:
        path: /etc/openvpn/server/easy-rsa
        owner: root
        group: root
        mode: '0755'
        recurse: yes

    - name: Initialize PKI
      command: ./easyrsa --batch init-pki
      args:
        chdir: /etc/openvpn/server/easy-rsa
    
    - name: Build CA
      command: ./easyrsa --batch build-ca nopass
      args:
        chdir: /etc/openvpn/server/easy-rsa

    - name: Generate server keys
      command: ./easyrsa --batch --days=3650 build-server-full server nopass
      args:
        chdir: /etc/openvpn/server/easy-rsa

    - name: Generate client keys
      command: ./easyrsa --batch --days=3650 build-client-full "client" nopass
      args:
        chdir: /etc/openvpn/server/easy-rsa

    - name: Generate CRL
      command: ./easyrsa --batch --days=3650 gen-crl
      args:
        chdir: /etc/openvpn/server/easy-rsa
    
    - name: Copy required files using cp command
      shell: >
        cp pki/ca.crt pki/private/ca.key pki/issued/server.crt pki/private/server.key pki/crl.pem /etc/openvpn/server
      args:
        chdir: /etc/openvpn/server/easy-rsa
    
    - name: Set permissions for CRL file
      file:
        path: /etc/openvpn/server/crl.pem
        owner: nobody
        group: nogroup
        mode: '0644'

    - name: Generate tls-crypt key
      command: openvpn --genkey secret /etc/openvpn/server/tc.key
      args:
        chdir: /etc/openvpn/server
    
    - name: Create dh.pem file
      copy:
        content: |
          -----BEGIN DH PARAMETERS-----
          MIIBCAKCAQEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
          +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
          87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
          YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
          7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
          ssbzSibBsu/6iGtCOGEoXJf//////////wIBAg==
          -----END DH PARAMETERS-----
        dest: /etc/openvpn/server/dh.pem
      
    - name: Generate server.conf
      copy:
        content: |
          local {{ my_command_output.stdout_lines[0] }}
          port 1194
          proto udp
          dev tun
          ca /etc/openvpn/server/ca.crt
          cert /etc/openvpn/server/server.crt
          key /etc/openvpn/server/server.key
          dh /etc/openvpn/server/dh.pem
          auth SHA512
          tls-crypt /etc/openvpn/server/tc.key
          topology subnet
          server 10.8.0.0 255.255.255.0
          push "redirect-gateway def1 bypass-dhcp"
          ifconfig-pool-persist ipp.txt
          push "dhcp-option DNS 8.8.8.8"
          push "dhcp-option DNS 8.8.4.4"
          push "block-outside-dns"
          keepalive 10 120
          cipher AES-256-CBC
          user nobody
          group nogroup
          persist-key
          persist-tun
          verb 3
          crl-verify /etc/openvpn/server/crl.pem
          explicit-exit-notify
        dest: /etc/openvpn/server/server.conf
    
    - name: enable ip forwording
      copy:
        content: |
          net.ipv4.ip_forward=1
        dest: /etc/sysctl.d/99-openvpn-forward.conf
    
    - name: Enable IP forwarding using sysctl module
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes

    - name: Create systemd service for iptables rules
      copy:
        content: |
          [Unit]
          Before=network.target
          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to {{ my_command_output.stdout_lines[0] }}
          ExecStart=/usr/sbin/iptables -I INPUT -p udp --dport 1194 -j ACCEPT
          ExecStart=/usr/sbin/iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
          ExecStart=/usr/sbin/iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
          ExecStop=/usr/sbin/iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to {{ my_command_output.stdout_lines[0] }}
          ExecStop=/usr/sbin/iptables -D INPUT -p udp --dport 1194 -j ACCEPT
          ExecStop=/usr/sbin/iptables -D FORWARD -s 10.8.0.0/24 -j ACCEPT
          ExecStop=/usr/sbin/iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
          RemainAfterExit=yes
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/openvpn-iptables.service

    - name: enable openvpn-Iptables service
      command: systemctl enable --now openvpn-iptables.service
    
    - name: enable openvpn-server
      command: systemctl enable --now openvpn-server@server.service

    - name: Read certificate files
      slurp:
        src: "/etc/openvpn/server/easy-rsa/pki/ca.crt"
      register: ca_cert

    - name: Read client certificate file
      slurp:
        src: "/etc/openvpn/server/easy-rsa/pki/issued/client.crt"
      register: client_cert

    - name: Read client private key file
      slurp:
        src: "/etc/openvpn/server/easy-rsa/pki/private/client.key"
      register: client_key

    - name: Read tls-crypt key file
      slurp:
        src: "/etc/openvpn/server/tc.key"
      register: tls_key

    - name: Generate the custom client.ovpn
      copy:
        dest: "~/client.ovpn"
        content: |
          client
          dev tun
          proto udp
          remote {{ my_command_output.stdout_lines[1] }} 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          auth SHA512
          cipher AES-256-CBC
          ignore-unknown-option block-outside-dns
          verb 3
          <ca>
          {{ ca_cert.content | b64decode }}
          </ca>
          <cert>
          {{ client_cert.content | b64decode }}
          </cert>
          <key>
          {{ client_key.content | b64decode }}
          </key>
          <tls-crypt>
          {{ tls_key.content | b64decode }}
          </tls-crypt>

    - name: Copy client.ovpn to /home/ubuntu
      copy:
        src: /root/client.ovpn
        dest: /home/ubuntu/
        remote_src: yes