name: AWS Connect
on:
  push:
    branches:
      - main
env:
  AWS_REGION : "us-east-1"   
permissions:
      id-token: write
      contents: read
jobs:
  DemoOIDC:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::076112249276:role/GitRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply Terraform
        run: terraform init && terraform apply -auto-approve
        working-directory: terraform

      - name: Store Private Key Content as Secret
        run: |
          PRIVATE_KEY_CONTENT=$(cat mykeypair.pem)
          echo "$PRIVATE_KEY_CONTENT" | \
            gh secret set MY_PRIVATE_KEY -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Apply Terraform state backup
      #   run: terraform init -backend-config="bucket=my-unique-bucket-name-333" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
      #   working-directory: terraform
      
      # - name: Upload Terraform State
      #   run: |
      #     aws s3 cp terraform/terraform.tfstate s3://my-unique-bucket-name-333/

      # - name: Extract Bucket Name
      #   id: extract_bucket_name
      #   run: echo "::set-output name=bucket_name::$(terraform output bucket_name)"
