#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com 
name: AWS Connect
on:
  push
env:
  AWS_REGION : "us-east-a"   
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  DemoOIDC:
    runs-on: demo
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::076112249276:role/GitRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply Terraform
        run: terraform init && terraform apply -auto-approve
        working-directory: terraform